### ISSUE TITLE
Migrate to chef-percona

### ISSUE THREAD

**Issue by armiller** [osuosl-cookbooks/osl-mysql#1]
The mysql community cookbook is not compatible with yum 3 and drops support for percona in the new releases. We need to migrate to a different cookbook to manage percona. I would recommend the chef-percona cookbook that is actively developed and maintained. https://github.com/phlipper/chef-percona

I also created a todo in trello. https://trello.com/b/k46l7JJo/chef-todo-s

**Comment by armiller** [comment]
I haven't touched osl-mysql in a long time but I'm pretty sure we did convert to percona. @jordane can you confirm?

**Comment by ramereth** [comment]
Confirmed.
